import 'package:joinme/src/models/chat.dart';
import 'package:joinme/src/models/event.dart';
import 'package:joinme/src/models/user.dart';
import 'package:latlong2/latlong.dart';

final currentUser = UserModel(
  id: 'user_01',
  name: 'Amina Bekele',
  avatarUrl: 'https://images.unsplash.com/photo-1502685104226-ee32379fefbe?auto=format&fit=crop&w=200&q=80',
  bio: 'City explorer and coffee collector. Always down for a last-minute adventure.',
  rating: 4.9,
  reviewCount: 38,
  eventsHosted: 12,
  eventsJoined: 28,
  friendsCount: 84,
  online: true,
  interests: ['Coffee', 'Soccer', 'Study', 'Food'],
);

final users = <UserModel>[
  currentUser,
  UserModel(
    id: 'user_02',
    name: 'Daniyal Tesfaye',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=200&q=80',
    bio: 'Event host and weekend strategist.',
    rating: 4.8,
    reviewCount: 21,
    eventsHosted: 9,
    eventsJoined: 17,
    friendsCount: 54,
    online: true,
    interests: ['Football', 'Photography', 'Travel'],
  ),
  UserModel(
    id: 'user_03',
    name: 'Sara Alem',
    avatarUrl: 'https://images.unsplash.com/photo-1544723795-3fb6469f5b39?auto=format&fit=crop&w=200&q=80',
    bio: 'Study buddy with an eye for playlists.',
    rating: 4.7,
    reviewCount: 15,
    eventsHosted: 5,
    eventsJoined: 20,
    friendsCount: 72,
    online: false,
    interests: ['Study', 'Design', 'Brunch'],
  ),
  UserModel(
    id: 'user_04',
    name: 'Mia Girma',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80',
    bio: 'Community builder working on spontaneous meetups.',
    rating: 4.6,
    reviewCount: 27,
    eventsHosted: 8,
    eventsJoined: 30,
    friendsCount: 91,
    online: true,
    interests: ['Hangouts', 'Food', 'Social'],
  ),
];

final events = <EventModel>[
  EventModel(
    id: 'event_01',
    title: 'Sunset Pickup Football',
    description: 'Join a quick 5-a-side match in the park and grab street coffee after.',
    category: EventCategory.sports,
    dateTime: DateTime.now().add(const Duration(hours: 6)),
    location: LatLng(9.0275, 38.7463),
    locationName: 'Gullele Sports Arena',
    hostId: 'user_02',
    maxParticipants: 10,
    participantIds: ['user_02', 'user_03'],
    rating: 4.9,
    duration: '2h',
  ),
  EventModel(
    id: 'event_02',
    title: 'Study Sprint + Notes Swap',
    description: 'Focused study session for design students with instant peer reviews.',
    category: EventCategory.study,
    dateTime: DateTime.now().add(const Duration(hours: 3, minutes: 30)),
    location: LatLng(9.0372, 38.7458),
    locationName: 'Bole Campus Cafe',
    hostId: 'user_03',
    maxParticipants: 8,
    participantIds: ['user_03'],
    rating: 4.7,
    duration: '1.5h',
  ),
  EventModel(
    id: 'event_03',
    title: 'Late Night Hangout',
    description: 'Chill playlist, board games, and new friends near Yeka.',
    category: EventCategory.social,
    dateTime: DateTime.now().add(const Duration(hours: 12)),
    location: LatLng(9.0426, 38.7600),
    locationName: 'Yeka Lounge',
    hostId: 'user_04',
    maxParticipants: 12,
    participantIds: ['user_04', 'user_01'],
    rating: 4.8,
    duration: '3h',
  ),
  EventModel(
    id: 'event_04',
    title: 'Brunch & Breakfast Club',
    description: 'Meet new people over a shared brunch table and coffee run.',
    category: EventCategory.food,
    dateTime: DateTime.now().add(const Duration(hours: 8)),
    location: LatLng(9.0211, 38.7572),
    locationName: 'Kazanchis Café',
    hostId: 'user_04',
    maxParticipants: 10,
    participantIds: ['user_04', 'user_02'],
    rating: 4.6,
    duration: '2h',
  ),
];

final chatThreads = <ChatThread>[
  ChatThread(
    id: 'chat_01',
    title: 'Pickup Football Squad',
    participantIds: ['user_01', 'user_02', 'user_03'],
    messages: [
      MessageModel(
        id: 'msg_01',
        senderId: 'user_02',
        text: 'I have some extra cones. Who is in for 6pm?',
        timestamp: DateTime.now().subtract(const Duration(minutes: 25)),
        isRead: false,
      ),
      MessageModel(
        id: 'msg_02',
        senderId: 'user_01',
        text: 'I’m in. Can we add one more defender?',
        timestamp: DateTime.now().subtract(const Duration(minutes: 18)),
        isRead: false,
      ),
    ],
    unreadCount: 2,
    isGroup: true,
    relatedEventId: 'event_01',
  ),
  ChatThread(
    id: 'chat_02',
    title: 'Study Sprint',
    participantIds: ['user_01', 'user_03'],
    messages: [
      MessageModel(
        id: 'msg_03',
        senderId: 'user_03',
        text: 'I found a great lib for our project notes.',
        timestamp: DateTime.now().subtract(const Duration(hours: 1, minutes: 12)),
        isRead: true,
      ),
    ],
    unreadCount: 0,
    isGroup: true,
    relatedEventId: 'event_02',
  ),
  ChatThread(
    id: 'chat_03',
    title: 'Amina & Daniyal',
    participantIds: ['user_01', 'user_02'],
    messages: [
      MessageModel(
        id: 'msg_04',
        senderId: 'user_02',
        text: 'Meet at the café before heading to the park?',
        timestamp: DateTime.now().subtract(const Duration(hours: 2, minutes: 8)),
        isRead: false,
      ),
    ],
    unreadCount: 1,
    isGroup: false,
    relatedEventId: null,
  ),
];
