// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOZWyz46im6dodYxIi2slgBcKp383FmF8',
    appId: '1:77110233609:web:2ed7f80dd4506f862086d8',
    messagingSenderId: '77110233609',
    projectId: 'joinme-19dd9',
    authDomain: 'joinme-19dd9.firebaseapp.com',
    storageBucket: 'joinme-19dd9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLj-xm8rziWtCQdWgLnP28bIOKH8Ipfq4',
    appId: '1:77110233609:android:5dfa645acca6e7d02086d8',
    messagingSenderId: '77110233609',
    projectId: 'joinme-19dd9',
    storageBucket: 'joinme-19dd9.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXnPGIjl1kExwv4Zz_HHIxlBM9U8wpiN8',
    appId: '1:77110233609:ios:fd2ee576355c246b2086d8',
    messagingSenderId: '77110233609',
    projectId: 'joinme-19dd9',
    storageBucket: 'joinme-19dd9.firebasestorage.app',
    iosClientId: '77110233609-job168151ouiiiu62v480veht5mpjg3t.apps.googleusercontent.com',
    iosBundleId: 'com.example.joinme',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXnPGIjl1kExwv4Zz_HHIxlBM9U8wpiN8',
    appId: '1:77110233609:ios:fd2ee576355c246b2086d8',
    messagingSenderId: '77110233609',
    projectId: 'joinme-19dd9',
    storageBucket: 'joinme-19dd9.firebasestorage.app',
    iosClientId: '77110233609-job168151ouiiiu62v480veht5mpjg3t.apps.googleusercontent.com',
    iosBundleId: 'com.example.joinme',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOZWyz46im6dodYxIi2slgBcKp383FmF8',
    appId: '1:77110233609:web:641f99cef28490bf2086d8',
    messagingSenderId: '77110233609',
    projectId: 'joinme-19dd9',
    authDomain: 'joinme-19dd9.firebaseapp.com',
    storageBucket: 'joinme-19dd9.firebasestorage.app',
  );
}
