// File generated by FlutterFire CLI or custom setup.
// ignore_for_file: type_annotation_public_api, objc_composed_formattable
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        return android;
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyYOUR-API-KEY-HERE',
    appId: '1:123456789012:web:a1b2c3d4e5f6',
    messagingSenderId: '123456789012',
    projectId: 'joinme-placeholder',
    authDomain: 'joinme-placeholder.firebaseapp.com',
    storageBucket: 'joinme-placeholder.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyYOUR-API-KEY-HERE',
    appId: '1:123456789012:android:a1b2c3d4e5f6',
    messagingSenderId: '123456789012',
    projectId: 'joinme-placeholder',
    storageBucket: 'joinme-placeholder.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyYOUR-API-KEY-HERE',
    appId: '1:123456789012:ios:a1b2c3d4e5f6',
    messagingSenderId: '123456789012',
    projectId: 'joinme-placeholder',
    storageBucket: 'joinme-placeholder.appspot.com',
    iosBundleId: 'com.example.joinme',
  );
}
